[versions]


[libraries]
android-gradlePlugin = "com.android.tools.build:gradle:7.0.0"
kotlin-gradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.20"
androidx-coreKtx = "androidx.core:core-ktx:1.6.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.1"
android-material = "com.google.android.material:material:1.4.0"
android-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.0"
junit = "junit:junit:4.13.2"

androidx-test-junit = "androidx.test.ext:junit:1.1.3"