name: Draft Release
on:
 push:
  tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      ORG_GRADLE_PROJECT_TAZABAZAR_RELEASE_PWD: ${{ secrets.ORG_GRADLE_PROJECT_TAZABAZAR_RELEASE_PWD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Decrypt Release Keystore
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
        run: ./scripts/decrypt_secrets.sh

      - name: Generate Cache key
        run: ./scripts/checksum.sh checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Build Project
        run: ./gradlew assembleDebug assembleRelease --stacktrace

      - name: Run Unit tests
        run: ./gradlew test -Pprod --stacktrace

      - name: Clean Secrets
        run: ./scripts/clean_secrets.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}